# Generated by Django 2.2.4 on 2019-11-07 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('collaboration_types', django_mysql.models.ListCharField(models.CharField(choices=[('image', 'image'), ('video', 'video'), ('programming', 'programming'), ('music', 'music'), ('performance', 'performance'), ('object', 'object'), ('idea', 'idea')], max_length=20), max_length=140, null=True, size=None)),
                ('creation_type', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('programming', 'programming'), ('music', 'music'), ('performance', 'performance'), ('object', 'object'), ('idea', 'idea')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collabo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('working', 'working'), ('completed', 'completed')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_dt', models.DateTimeField(db_index=True, null=True)),
                ('end_dt', models.DateTimeField(db_index=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('main_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Artist')),
                ('sub_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteCollabos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Collabo')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_collabos', to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteArtists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Artist')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(null=True)),
                ('thumbnail_url', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('color', models.CharField(max_length=10)),
                ('created_dt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arts', to='api.Artist')),
            ],
        ),
    ]
