# Generated by Django 2.2.4 on 2019-11-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteArtists',
            new_name='FavoriteArtist',
        ),
        migrations.RenameModel(
            old_name='FavoriteCollabos',
            new_name='FavoriteCollabo',
        ),
        migrations.AlterField(
            model_name='collabo',
            name='status',
            field=models.CharField(choices=[('waiting', 'waiting'), ('working', 'working'), ('completed', 'completed')], db_index=True, default='waiting', max_length=20),
        ),
    ]
