# Generated by Django 2.2.4 on 2019-11-14 08:20

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_collabo_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='art',
            name='url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='url',
        ),
        migrations.AddField(
            model_name='art',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Art.image_upload_path),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.Artist.image_upload_path),
        ),
    ]
